# First experiment with three platforms:
# Cirq, Qiskit, Pyquil
# first with Qconvert


# GLOBAL

min_n_qubits: 2
max_n_qubits: 20
min_n_ops: 30
max_n_ops: 200
random_seed: 42

# EXECUTABLE PATH
qconvert_path: ../node_converter/qconvert-js/cli.js
python_path: /home/XXXX-1/.conda/envs/ML4Quantum/bin/python3


# PROGRAM GENERATION
program_id_pattern: "{{timestamp}}_{{qasm_hash}}_{{randint}}"
gate_set:
  cx: 3
  rx: 1
  ry: 1
  rz: 1
  p: 1
n_generated_programs: 100

# EXECUTION
strategy_sample_size_estimation: null
fixed_sample_size: 8192

# DETECTORS
detectors:
  - name: ks
    test_long_name: Kolmogorov–Smirnov Test
    detector_object: KS_Detector

# FOLDERS
experiment_folder: ../data/experiment_v03/

comparisons:
  - name: cross_platform
    description: |
      Sample A: random program x, executed on Qiskit.
      Sample B: random program x, executed on Circ.
      Sample C: random program x, executed on Pyquil.
    title: Qiskit vs Cirq vs Pyquil
    expected_divergence: false
    generation_object: WeightedRandomCircuitGenerator
    compilers:
      - name: qiskit
      - name: cirq
      - name: pyquil



