# First try of cross-platform comparison (no ground truth available)

# GLOBAL

min_n_qubits: 2
max_n_qubits: 20
min_n_ops: 30
max_n_ops: 200
random_seed: 42

# PROGRAM GENERATION
program_id_pattern: "{{timestamp}}_{{qasm_hash}}_{{randint}}"
gate_set:
  cx: 3
  rx: 1
  ry: 1
  rz: 1
  p: 1
n_generated_programs: 1000

# EXECUTION
strategy_sample_size_estimation: null # "qdiff[cited paper]" | null
fixed_sample_size: 8192
n_repetitions: 10
strategy_input_generation: null
fixed_input: 0

# DETECTORS
detectors:
  - name: ks
    test_long_name: Kolmogorov–Smirnov Test
    detector_object: KS_Detector
  #- name: energy
  #  test_long_name: Energy Test
  #  detector_object: Energy_Detector
  #  parallel_execution: true
  #  random_seed: 1234


# FOLDERS
folder_benchmark: ../data/experiment_v02/

benchmarks_configurations:
  - name: cross_platform
    description: |
      Sample A: random program x, executed on Qiskit.
      Sample B: random program x, executed on Circ.
    title: Random Program Qiskit vs Random Program Cirq
    expected_divergence: false
    samples_relationship: identical
    generation_object: WeightedRandomCircuitGenerator
    sample_a:
      execution_object: QiskitCircuit
    sample_b:
      execution_object: CirqCircuit



