# Real algorithms with Qconvert and same number of shots = 8192 :
# Cirq, Qiskit

# Dataset of real programs
# - Famous Algorithms from QASMBench Medium (only 11/17)
# - TKet QASM benchmark programs (only those which were from the publication
#   arxiv-2003-10611 (qasm file folder), those with less or equeal than 20 qubits
#   with exactly one quantum register and one classical register and the
#   size of the classical register is equal or bigger than the quantum. Then the
#   quantum register is completely measured.)

# Every platform executes the same programs multiple times so that all
# combinations of two platform executions are used to create a more
# reliable p-value. In that way only very discordant cases will be highlighted.

# Here we care about the expected_divergence keyword.

# !!! CHANGE FOLDER TO NOT OVERRIDE THE RESULTS




# FOLDERS
experiment_folder: ../data/experiment_v06/

# GLOBAL

min_n_qubits: 2
max_n_qubits: 20
min_n_ops: 30
max_n_ops: 200
random_seed: 42

# EXECUTABLE PATH
qconvert_path: ../node_converter/qconvert-js/cli.js
python_path: /home/XXXX-1/.conda/envs/ML4Quantum/bin/python3


# PROGRAM GENERATION
program_id_pattern: "{{timestamp}}_{{qasm_hash}}_{{randint}}"
gate_set:
  cx: 3
  rx: 1
  ry: 1
  rz: 1
  p: 1
n_generated_programs: 500


# EXECUTION
strategy_sample_size_estimation: null
fixed_sample_size: 8192
n_executions: 5

# DETECTORS
detectors:
  - name: ks
    test_long_name: Kolmogorov–Smirnov Test
    detector_object: KS_Detector

comparisons:
  - name: cross_platform
    description: |
      Sample A: random program x, executed on Qiskit.
      Sample B: random program x, executed on Circ.
    title: Qiskit vs Cirq
    generation_object: WeightedRandomCircuitGenerator
    compilers:
      - name: qiskit
        shots_lookup: "shots = 1024"
        shots_substitute: "shots = {injected_shot}"
      - name: cirq
        shots_lookup: "repetitions=1024"
        shots_substitute: "repetitions={injected_shot}"
#- name: pyquil
#  shots_lookup: "shots = 1024"
#  shots_substitute: "shots = {injected_shot}"
  - name: qasm_bench_mid
    description: |
      Sample A: real program x, executed on Cirq.
      Sample B: real program x, executed on Qiskit.
    title: QasmBench Medium Size - Qiskit vs Cirq
    is_benchmark: true
    expected_divergence: false
    generation_object: QasmMidCircuitGenerator
    compilers:
      - name: qiskit
        shots_lookup: "shots = 1024"
        shots_substitute: "shots = {injected_shot}"
      - name: cirq
        shots_lookup: "repetitions=1024"
        shots_substitute: "repetitions={injected_shot}"
  - name: tket_bench_1
    description: |
      Sample A: real program x, executed on Cirq.
      Sample B: real program x, executed on Qiskit.
    title: TKet Benchmark 1 - Qiskit vs Cirq
    is_benchmark: true
    expected_divergence: false
    generation_object: TketCircuitGenerator
    compilers:
      - name: qiskit
        shots_lookup: "shots = 1024"
        shots_substitute: "shots = {injected_shot}"
      - name: cirq
        shots_lookup: "repetitions=1024"
        shots_substitute: "repetitions={injected_shot}"